/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clientesbac;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author DIEGO
 */
public class frmConfiguracion extends javax.swing.JFrame {

    String url = "";
    boolean cambiarLogo = false;
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Recursos/bac_icono.png"));
        return retValue;
    }
    /**
     * Creates new form frmConfiguracion
     */
    public frmConfiguracion() {
        initComponents();
        iniciarObjetos();
    }
    
    public void iniciarObjetos()
    {
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de imagen", "jpg", "png");
        jFileChooser1.setFileFilter(filter);
    }
    
    public void procesarJfileChooser1() {
        int seleccion = jFileChooser1.showOpenDialog(this); 

        if (seleccion == JFileChooser.APPROVE_OPTION) { 
            try { 
                File file = jFileChooser1.getSelectedFile(); 
                //Obteniendo la direccion del archivo
                url = file.getPath();
                
                ImageIcon img = new ImageIcon(url); 
                ImageIcon imgRedimensionada = new ImageIcon(img.getImage().getScaledInstance(110, 110, 0));
                jLabelImg.setIcon(imgRedimensionada);
                
            }
            catch(Exception es) {
                JOptionPane.showMessageDialog(null, "Error al abrir el archivo"+ es);
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelImg = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerCajas = new javax.swing.JSpinner();

        jFileChooser1.setAcceptAllFileFilterUsed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración");
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuración");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 520, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Número de Cajas:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 210, 170, 32);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 280, 180, 80);

        jLabelImg.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabelImg);
        jLabelImg.setBounds(570, 140, 110, 110);

        jButton2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton2.setText("Cargar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 140, 180, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 90, 740, 10);

        jButton3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 320, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Logo del Programa:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 140, 200, 32);

        jSpinnerCajas.setModel(new javax.swing.SpinnerNumberModel(5, 1, 50, 1));
        getContentPane().add(jSpinnerCajas);
        jSpinnerCajas.setBounds(320, 210, 180, 26);

        setSize(new java.awt.Dimension(757, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        procesarJfileChooser1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide(); this.dispose();
        frmMenuPrincipal f1 = new frmMenuPrincipal();
        f1.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!url.equals(""))
        {
            cambiarLogo = true;
            try{
                if (cambiarLogo == true){
                    clientesbac.clientesBac.g.setImagen(url);
                    System.out.println("Imagen Procesada");
                }

                clientesbac.clientesBac.cajasCola = new ListaC((Integer)jSpinnerCajas.getValue());
                System.out.println(clientesbac.clientesBac.cajasCola.getSize());
                System.out.println(clientesbac.clientesBac.cajasCola.getLast().getNombre());

                JOptionPane.showMessageDialog(null, "Datos procesados Correctamente","Error",JOptionPane.INFORMATION_MESSAGE);
                this.hide(); this.dispose();
                frmMenuPrincipal f1 = new frmMenuPrincipal();
                f1.show();
            }
            catch(Exception e){}
        }
        else{
            JOptionPane.showMessageDialog(null, "Faltan datos por completar","Mensaje de error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        //Esta instruccion aplica el skin
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.NebulaSkin");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerCajas;
    // End of variables declaration//GEN-END:variables
}
